// Labelled design examples. Shown only while there are no real records, never stored in the database.
export const exampleNeeds = [
  { id: "example-data-tools", title: "Improve community data tools", output: "A simple data collection template and a training session so the team can run it alone.", description: "Our field officers visit 40 villages every month to check water points. Each records results differently, on paper and in three spreadsheets, so we cannot compare months or show what has changed. We need one simple way to collect the same information every time.", hours: 12, arrangement: "Remote", languages: ["English", "Swahili"], skills: ["Data analysis", "MEL", "Training"], organisation: { name: "Water for Tomorrow", city: "Nakuru", country: "Kenya", summary: "A community organisation maintaining safe water points with village committees." }, deliverables: ["A data collection template that works offline on a phone", "A one-page guide for field officers", "A 90-minute remote training session", "A short handover note"] },
  { id: "example-donor-research", title: "Donor research and grant narrative", output: "A shortlist of 20 aligned funders and a reusable funding narrative.", description: "We run language and employment support for refugee women. We rely on two funders and need to find others whose priorities match our work.", hours: 8, arrangement: "Remote", languages: ["French", "English"], skills: ["Fundraising", "Research"], organisation: { name: "Refugee Women Rise", city: "Lyon", country: "France", summary: "Language and employment support for refugee women." }, deliverables: ["A shortlist of 20 funders with deadlines", "A two-page funding narrative"] },
  { id: "example-finance-toolkit", title: "Practical financial toolkit", output: "A budgeting toolkit and a short team training session.", description: "Our small team manages three grants in separate spreadsheets. We need a simple budget template and a way to track spending against each grant.", hours: 10, arrangement: "Remote", languages: ["English", "isiXhosa"], skills: ["Finance", "Training"], organisation: { name: "Green Futures Collective", city: "Cape Town", country: "South Africa", summary: "Urban food gardens run with local schools." }, deliverables: ["A budget template", "A 60-minute training session"] },
  { id: "example-accessible-events", title: "Accessible presentations and training", output: "A presentation template and guidance staff can use for every event.", description: "We run training for disability advocates. Our slides and handouts are hard to read for some participants.", hours: 6, arrangement: "Remote", languages: ["English", "Ghanaian Sign Language"], skills: ["Accessibility", "Design"], organisation: { name: "Inclusive Futures", city: "Accra", country: "Ghana", summary: "Training and advocacy with disabled people’s organisations." }, deliverables: ["An accessible slide template", "A one-page checklist"] },
  { id: "example-documentary", title: "Edit a youth-led short documentary", output: "A 6-minute edit ready to screen, plus a 60-second trailer.", description: "Young people filmed their own stories about climate and jobs. We need help turning 4 hours of footage into a short film.", hours: 16, arrangement: "Remote", languages: ["English", "Yoruba"], skills: ["Video editing", "Storytelling"], organisation: { name: "Youth Voice Collective", city: "Ibadan", country: "Nigeria", summary: "Media training for young people." }, deliverables: ["A 6-minute edit", "A 60-second trailer"] },
  { id: "example-recruitment", title: "Inclusive recruitment process", output: "A reviewed recruitment process with practical recommendations.", description: "We are hiring our first five staff and want a fair, inclusive process from the start.", hours: 14, arrangement: "Hybrid", languages: ["Swahili", "English"], skills: ["Human resources", "Policy"], organisation: { name: "Equal Access Network", city: "Kisumu", country: "Kenya", summary: "Community legal information and referrals." }, deliverables: ["A reviewed recruitment process", "Interview guidance"] },
].map((n) => ({ ...n, example: true, status: "open", created_at: "2026-09-01" }));

export const exampleProfile = {
  user_id: "example-maria-lopez", example: true, name: "Maria Lopez", headline: "UX designer · research · accessibility", location: "Madrid", country: "Spain",
  languages: ["English", "Spanish"], hours_available: 16, arrangement: "Remote", skills: ["UX research", "Accessibility", "Figma", "User testing", "UX design", "Content"],
  bio: "I help purpose-led organisations make digital services easier for everyone to use. My work combines research, accessible design and practical tools small teams can maintain.",
  experience: "Senior UX designer, public-sector studio · 2021 to now\nUX researcher, digital agency · 2018 to 2021", contributions: 3,
};

export const exampleContributions = [
  { id: "ex1", need_title: "Accessibility review", organisation: "Example Organisation", organisation_country: "Spain", need: "The website was hard to use with a screen reader, and donations dropped on mobile.", output: "A prioritised list of fixes the web volunteer can act on.", deliverables: "A prioritised list of 23 fixes\nAnnotated designs for the donation page\nA one-hour handover with the web volunteer", endorsement: "Very detailed, practical recommendations our team was able to implement straight away.", endorsed_by_role: "Communications lead", hours: 12, period: "August 2026", still_in_use: true, skills: ["UX research", "Accessibility", "Figma"] },
  { id: "ex2", need_title: "Service journey user testing", organisation: "Inclusive Futures", organisation_country: "Ghana", need: "People gave up halfway through signing up for a training programme.", output: "Tested improvements to the sign-up journey.", deliverables: "Findings report with video clips\nA redesigned three-step sign-up\nA testing guide the team can reuse", endorsement: "Maria turned user feedback into a clear set of changes and helped us prioritise them.", endorsed_by_role: "Programme manager", hours: 16, period: "July 2026", skills: ["UX research", "User testing"] },
  { id: "ex3", need_title: "Donation flow redesign", organisation: "Refugee Women Rise", organisation_country: "France", need: "Online donations were low and the form asked for too much information.", output: "A shorter, bilingual donation form.", deliverables: "A shorter donation form in French and English\nA style guide for campaign pages", endorsement: "Clear, generous and fast. The new form is simpler for our supporters.", endorsed_by_role: "Co-founder", hours: 14, period: "June 2026", still_in_use: true, skills: ["UX design", "Accessibility", "Content"] },
];
