// Labelled design examples. Shown only while there are no real records, never stored in the database.
export const exampleNeeds = [
  { id: "example-data-tools", title: "Improve community data tools", output: "A simple data collection template and a training session so the team can run it alone.", description: "Our field officers visit 40 villages every month to check water points. Each records results differently, on paper and in three spreadsheets, so we cannot compare months or show what has changed. We need one simple way to collect the same information every time.", hours: 12, arrangement: "Remote", languages: ["English", "Swahili"], skills: ["Data analysis", "MEL", "Training"], organisation: { name: "Water for Tomorrow", city: "Nakuru", country: "Kenya", summary: "A community organisation maintaining safe water points with village committees." }, deliverables: ["A data collection template that works offline on a phone", "A one-page guide for field officers", "A 90-minute remote training session", "A short handover note"] },
  { id: "example-donor-research", title: "Donor research and grant narrative", output: "A shortlist of 20 aligned funders and a reusable funding narrative.", description: "We run language and employment support for refugee women. We rely on two funders and need to find others whose priorities match our work.", hours: 8, arrangement: "Remote", languages: ["French", "English"], skills: ["Fundraising", "Research"], organisation: { name: "Refugee Women Rise", city: "Lyon", country: "France", summary: "Language and employment support for refugee women." }, deliverables: ["A shortlist of 20 funders with deadlines", "A two-page funding narrative"] },
  { id: "example-finance-toolkit", title: "Practical financial toolkit", output: "A budgeting toolkit and a short team training session.", description: "Our small team manages three grants in separate spreadsheets. We need a simple budget template and a way to track spending against each grant.", hours: 10, arrangement: "Remote", languages: ["English", "isiXhosa"], skills: ["Finance", "Training"], organisation: { name: "Green Futures Collective", city: "Cape Town", country: "South Africa", summary: "Urban food gardens run with local schools." }, deliverables: ["A budget template", "A 60-minute training session"] },
  { id: "example-accessible-events", title: "Accessible presentations and training", output: "A presentation template and guidance staff can use for every event.", description: "We run training for disability advocates. Our slides and handouts are hard to read for some participants.", hours: 6, arrangement: "Remote", languages: ["English", "Ghanaian Sign Language"], skills: ["Accessibility", "Design"], organisation: { name: "Inclusive Futures", city: "Accra", country: "Ghana", summary: "Training and advocacy with disabled people’s organisations." }, deliverables: ["An accessible slide template", "A one-page checklist"] },
  { id: "example-documentary", title: "Edit a youth-led short documentary", output: "A 6-minute edit ready to screen, plus a 60-second trailer.", description: "Young people filmed their own stories about climate and jobs. We need help turning 4 hours of footage into a short film.", hours: 16, arrangement: "Remote", languages: ["English", "Yoruba"], skills: ["Video editing", "Storytelling"], organisation: { name: "Youth Voice Collective", city: "Ibadan", country: "Nigeria", summary: "Media training for young people." }, deliverables: ["A 6-minute edit", "A 60-second trailer"] },
  { id: "example-recruitment", title: "Inclusive recruitment process", output: "A reviewed recruitment process with practical recommendations.", description: "We are hiring our first five staff and want a fair, inclusive process from the start.", hours: 14, arrangement: "Hybrid", languages: ["Swahili", "English"], skills: ["Human resources", "Policy"], organisation: { name: "Equal Access Network", city: "Kisumu", country: "Kenya", summary: "Community legal information and referrals." }, deliverables: ["A reviewed recruitment process", "Interview guidance"] },
].map((n) => ({ ...n, example: true, status: "open", created_at: "2026-09-01" }));

// The founder's own profile, shown as the sample impact CV until real profiles are approved.
// Her real work; organisations have not endorsed it yet, so every contribution is marked "endorsement pending" and no hours are claimed.
export const exampleProfile = {
  user_id: "julieta-castineira-de-dios", example: true, founder: true, name: "Julieta Castiñeira de Dios", headline: "Lawyer · strategist · organisation builder", location: "Anywhere · remote", country: "",
  languages: ["English", "Spanish", "Portuguese"], hours_available: null, arrangement: "Remote",
  skills: ["Strategy", "Theory of change", "Compliance and risk", "Branding", "Partnerships", "Legal", "Programme management", "Research"],
  bio: "I help purpose-led organisations turn a meaningful vision into a clear strategy, workable systems and confident next steps. I founded Ethical Bridge and took it from an idea to an organisation ready to launch over three and a half years, and I built Handova so local teams can reach skills like these for free.",
  experience: "Founder · Ethical Bridge\nFounder · Method into Impact\nFounder · Local Impact Alliance (being registered)\nInternational development · Programme and development management\nAwards and compliance · Project administration\nAcademic research\nLegal practice · Argentina, including the Public Ministry of Defence",
  background: [
    ["Organisations", ["Save the Children", "Lutheran World Federation", "Consulting Base", "AdvocAid"]],
    ["Regions", ["Argentina and South America", "Australia", "Europe", "Africa"]],
    ["Education", ["Law degree", "Master in African Studies"]],
  ],
  website: "", linkedin: "", photo: "assets/julieta-castineira-de-dios.jpg", contributions: 3,
};

export const exampleContributions = [
  { id: "jc-hwh", need_title: "Brand, strategic direction and theory of change", organisation: "Hands With Heart Foundation", need: "A brand and a written strategy for the foundation.", output: "A brand manual, a strategic direction and a theory of change.", deliverables: "Brand manual\nStrategic direction\nTheory of change", skills: ["Branding", "Strategy", "Theory of change"], pending: true, public: true },
  { id: "jc-asri", need_title: "Compliance and risk tool", organisation: "ASRI", need: "A way to manage compliance and risk.", output: "A compliance and risk tool.", deliverables: "Compliance and risk tool", skills: ["Compliance and risk", "Legal"], pending: true, public: true },
  { id: "jc-hopes", need_title: "Branding", organisation: "HOPES", need: "A brand for the organisation.", output: "A brand identity.", deliverables: "Brand identity", skills: ["Branding", "Design"], pending: true, public: true },
];
