// Labelled design examples. Shown only while there are no real records, never stored in the database.
export const exampleNeeds = [
  { id: "example-data-tools", title: "Improve community data tools", output: "A simple data collection template and a training session so the team can run it alone.", description: "Our field officers visit 40 villages every month to check water points. Each records results differently, on paper and in three spreadsheets, so we cannot compare months or show what has changed. We need one simple way to collect the same information every time.", hours: 12, arrangement: "Remote", languages: ["English", "Swahili"], skills: ["Data analysis", "Monitoring and evaluation (MEL)", "Training"], organisation: { name: "Water for Tomorrow", city: "Nakuru", country: "Kenya", summary: "A community organisation maintaining safe water points with village committees." }, deliverables: ["A data collection template that works offline on a phone", "A one-page guide for field officers", "A 90-minute remote training session", "A short handover note"] },
  { id: "example-donor-research", title: "Donor research and grant narrative", output: "A shortlist of 20 aligned funders and a reusable funding narrative.", description: "We run language and employment support for refugee women. We rely on two funders and need to find others whose priorities match our work.", hours: 8, arrangement: "Remote", languages: ["French", "English"], skills: ["Fundraising", "Research"], organisation: { name: "Refugee Women Rise", city: "Lyon", country: "France", summary: "Language and employment support for refugee women." }, deliverables: ["A shortlist of 20 funders with deadlines", "A two-page funding narrative"] },
  { id: "example-finance-toolkit", title: "Practical financial toolkit", output: "A budgeting toolkit and a short team training session.", description: "Our small team manages three grants in separate spreadsheets. We need a simple budget template and a way to track spending against each grant.", hours: 10, arrangement: "Remote", languages: ["English", "isiXhosa"], skills: ["Financial management", "Training"], organisation: { name: "Green Futures Collective", city: "Cape Town", country: "South Africa", summary: "Urban food gardens run with local schools." }, deliverables: ["A budget template", "A 60-minute training session"] },
  { id: "example-accessible-events", title: "Accessible presentations and training", output: "A presentation template and guidance staff can use for every event.", description: "We run training for disability advocates. Our slides and handouts are hard to read for some participants.", hours: 6, arrangement: "Remote", languages: ["English", "Ghanaian Sign Language"], skills: ["Accessibility", "Graphic design"], organisation: { name: "Inclusive Futures", city: "Accra", country: "Ghana", summary: "Training and advocacy with disabled people’s organisations." }, deliverables: ["An accessible slide template", "A one-page checklist"] },
  { id: "example-documentary", title: "Edit a youth-led short documentary", output: "A 6-minute edit ready to screen, plus a 60-second trailer.", description: "Young people filmed their own stories about climate and jobs. We need help turning 4 hours of footage into a short film.", hours: 16, arrangement: "Remote", languages: ["English", "Yoruba"], skills: ["Video editing", "Storytelling"], organisation: { name: "Youth Voice Collective", city: "Ibadan", country: "Nigeria", summary: "Media training for young people." }, deliverables: ["A 6-minute edit", "A 60-second trailer"] },
  { id: "example-recruitment", title: "Inclusive recruitment process", output: "A reviewed recruitment process with practical recommendations.", description: "We are hiring our first five staff and want a fair, inclusive process from the start.", hours: 14, arrangement: "Hybrid", languages: ["Swahili", "English"], skills: ["Human resources", "Policy"], organisation: { name: "Equal Access Network", city: "Kisumu", country: "Kenya", summary: "Community legal information and referrals." }, deliverables: ["A reviewed recruitment process", "Interview guidance"] },
].map((n) => ({ ...n, example: true, status: "open", created_at: "2026-09-01" }));

// The founder's own profile, shown as the sample impact CV until real profiles are approved.
// Her real work; organisations have not endorsed it yet, so every contribution is marked "endorsement pending" and no hours are claimed.
export const exampleProfile = {
  user_id: "julieta-castineira-de-dios", example: true, founder: true, name: "Julieta Castiñeira de Dios", headline: "Lawyer · strategist · organisation builder", location: "Anywhere · remote", country: "",
  languages: ["English", "Spanish", "Portuguese"], hours_available: null, arrangement: "Remote",
  skills: ["Strategy", "Theory of change", "Programme management", "Legal", "Policy", "Compliance and risk", "Governance", "Research", "Monitoring and evaluation (MEL)", "Fundraising", "Partnerships", "Communications", "Branding", "Graphic design", "Inclusion", "Human resources", "Training", "Digital tools"],
  bio: "I help purpose-led organisations turn a meaningful vision into a clear strategy, workable systems and confident next steps. I founded Ethical Bridge and took it from an idea to an organisation ready to launch over three and a half years, and I built Handova so local teams can reach skills like these for free.",
  // Same shape as real profiles. Titles, years and universities still to confirm from her LinkedIn are left blank, not guessed.
  experience_items: [
    { title: "Founder", organisation: "Ethical Bridge", employment_type: "Self-employed", start: "2026-04", end: "present", country: "", work_mode: "Remote", description: "Founder of Ethical Bridge, a platform connecting purpose-driven individuals with ethical organisations worldwide through meaningful opportunities, visibility, and responsible global collaboration.", skills: [] },
    { title: "Project and Awards Coordinator", organisation: "Save the Children Australia", employment_type: "Full-time", start: "2026-01", end: "present", country: "", work_mode: "Remote", description: "The Project and Award Coordinator is a pivotal Head Office role to support Save the Children Australia’s Pacific development and humanitarian programs with award and project support.", skills: [] },
    { title: "Founder", organisation: "Method into Impact", employment_type: "", start: "", end: "present", country: "", work_mode: "", description: "", skills: [] },
    { title: "Founder", organisation: "Local Impact Alliance (being registered)", employment_type: "", start: "", end: "present", country: "Ireland", work_mode: "", description: "", skills: [] },
    { title: "", organisation: "Consulting Base Limited", employment_type: "Freelance", start: "", end: "", country: "", work_mode: "", description: "", skills: [] },
    { title: "", organisation: "Save the Children Denmark", employment_type: "", start: "", end: "", country: "Denmark", work_mode: "", description: "", skills: [] },
    { title: "", organisation: "AdvocAid", employment_type: "", start: "", end: "", country: "Sierra Leone", work_mode: "", description: "", skills: [] },
    { title: "", organisation: "Lutheran World Federation", employment_type: "", start: "", end: "", country: "", work_mode: "", description: "", skills: [] },
    { title: "", organisation: "Public Ministry of Defence", employment_type: "", start: "", end: "", country: "Argentina", work_mode: "", description: "", skills: [] },
  ],
  education_items: [
    { organisation: "", title: "Master of Laws (LLM)", field: "Law", start: "", end: "", country: "", description: "" },
    { organisation: "", title: "Bachelor of Laws (LLB)", field: "Law", start: "", end: "", country: "", description: "" },
    { organisation: "", title: "Master’s degree", field: "Regional studies (e.g. African, Latin American)", start: "", end: "", country: "", description: "African Studies" },
    { organisation: "", title: "Diploma", field: "Criminology and forensic science", start: "", end: "", country: "", description: "" },
  ],
  website: "", linkedin: "", photo_url: "", photo: "assets/julieta-castineira-de-dios.jpg", contributions: 3,
};

export const exampleContributions = [
  { id: "jc-asri", need_link: "#organisations/asri", org_page: "#organisations/asri", need_title: "Compliance and risk tool", organisation: "Alam Sehat Lestari (ASRI)", organisation_country: "Indonesia", org_url: "https://ethicalbridge.org/organisations/02459f0b-bf16-4736-a427-7757c7254b56/", org_logo: "https://jyvralzxqftdextjowwf.supabase.co/storage/v1/object/public/organisation-logos/02459f0b-bf16-4736-a427-7757c7254b56/1785721781422-ornament-asri-logo.png", hours: 4, need: "A practical way for the team to manage its compliance and risk.", output: "A compliance and risk tool the team can keep using.", deliverables: "Compliance and risk tool", skills: ["Compliance and risk", "Legal"], pending: true, public: true },
  { id: "jc-hwh", need_link: "#organisations/hwh", org_page: "#organisations/hwh", need_title: "Brand, strategic direction and theory of change", organisation: "Hands With Heart Foundation", organisation_country: "Spain", org_url: "https://ethicalbridge.org/organisations/2544786e-4bd6-4ee8-8fd2-5ca309f9edbf/", org_logo: "https://ethicalbridge.org/assets/logos/2544786e-4bd6-4ee8-8fd2-5ca309f9edbf.svg", hours: 3, need: "A brand and a written strategy the foundation can share with funders and partners.", output: "A brand manual, a strategic direction and a theory of change.", deliverables: "Brand manual\nStrategic direction\nTheory of change", skills: ["Branding", "Strategy", "Theory of change"], pending: true, public: true },
  { id: "jc-hopes", need_link: "#organisations/hopes", org_page: "#organisations/hopes", need_title: "Branding", organisation: "HOPES", hours: 1, need: "A brand for the organisation.", output: "A brand identity.", deliverables: "Brand identity", skills: ["Branding", "Graphic design"], pending: true, public: true },
];

// Real needs the founder has already handed over.
// One record per need: the organisation page, the Needs list and the impact CV are three views of the
// same entry (exampleContributions above + the organisation below), never separate copies.
const ORG_INFO = {
  asri: { name: "Alam Sehat Lestari (ASRI)", city: "Sukadana", country: "Indonesia", summary: "An Indonesian organisation connecting healthcare, forest conservation and sustainable livelihoods for communities near high-value forests.", ethical_bridge_url: "https://ethicalbridge.org/organisations/02459f0b-bf16-4736-a427-7757c7254b56/" },
  hwh: { name: "Hands With Heart Foundation", city: "Barcelona", country: "Spain", summary: "A Barcelona-based foundation that brings volunteer health professionals to underserved communities to give free care to children and adults with disabilities, and trains local practitioners.", ethical_bridge_url: "https://ethicalbridge.org/organisations/2544786e-4bd6-4ee8-8fd2-5ca309f9edbf/" },
  hopes: { name: "HOPES", city: "", country: "", summary: "", ethical_bridge_url: "" },
};
const key = (c) => c.id.slice(3);
export const handovaOrgs = Object.entries(ORG_INFO).map(([id, o]) => ({ id, ...o, logo: exampleContributions.find((c) => key(c) === id)?.org_logo || "" }));
export const solvedNeeds = exampleContributions.map((c) => ({
  id: "done-" + key(c), org_id: key(c), handed: true, status: "completed", title: c.need_title, description: c.need, output: c.output, deliverables: String(c.deliverables || "").split(/\n+/).filter(Boolean),
  hours: c.hours, arrangement: "Remote", languages: ["English"], skills: c.skills, organisation: { id: key(c), ...ORG_INFO[key(c)] }, logo: c.org_logo,
  contributor: { name: exampleProfile.name, id: exampleProfile.user_id, photo: exampleProfile.photo }, pending: c.pending, created_at: "2026-09-01",
}));
