export const guides = {
  guide: [
    "How it works",
    "Professional support, with clear expectations.",
    `<h2>For talent</h2><ol><li>Create your profile, describe your experience and set realistic monthly availability.</li><li>Add previous work to your portfolio. Explain your role and outcomes, and only share material you have permission to publish.</li><li>Publish your profile to appear in the directory. Explore needs, save interesting ones and apply with a specific explanation of how you can help.</li><li>Check your workspace for decisions and invitations. Before starting, agree on scope, timing, access, safeguarding and communication directly with the organisation.</li><li>Log contributions after your application or invitation is accepted. The organisation reviews them; approval is recorded separately from self-reported portfolio claims.</li></ol><h2>For organisations</h2><ol><li>Use your Ethical Bridge organisation account. An existing organisation member can manage the workspace; new organisations start through Ethical Bridge.</li><li>Write a clear need: expected output, required skills, estimated hours and working arrangements. Drafts stay private until your organisation is published and you open the need.</li><li>Browse talent profiles and portfolios, invite suitable people and review applications.</li><li>Agree on the engagement directly. Review submitted time with a clear explanation when changes are needed.</li><li>Close the need when you stop accepting applications.</li></ol><h2>Keep the relationship clear</h2><p>Impact Accelerator supports professional, voluntary contributions. It does not process payments or replace a written agreement. Confirm expenses, ownership of outputs, confidentiality and any regulated requirements before starting.</p>`,
  ],
  privacy: [
    "Privacy & storage",
    "You choose what you share.",
    `<h2>Public and private information</h2><p>Profiles start private. Publishing makes your name, professional details, location, skills and availability visible in the directory. Portfolio entries have their own draft/public setting; they are visible publicly only when both the entry and its profile are published. Do not put private contact details or beneficiary information in public fields.</p><p>Applications, invitations, conversations and time entries are visible to the participating professional and the relevant organisation members. Account email addresses are managed by Supabase Auth and are not displayed in the public directory.</p><h2>Storage and external services</h2><p>Account and platform records are stored in Ethical Bridge’s Supabase service. Authentication uses browser storage to keep you signed in. Sign out on shared devices. This app does not include advertising or analytics trackers, so there are no optional analytics cookies to accept.</p><p>Uploaded thumbnails use private storage and time-limited viewing links. A previously issued link can remain valid for up to one hour after unpublishing. Alternatively, thumbnails load from the external HTTPS address supplied by their author. The image provider receives a network request, including the visitor’s IP address; the app sends no referrer. Supporting links open external sites with their own privacy practices.</p><h2>Control your information</h2><p>Unpublish your profile or an entry to remove it from public browsing. You can edit your profile, delete portfolio entries, export your portfolio, and withdraw pending applications. Submitted contribution and review records remain available to the participants for accountability. For account deletion or other data requests, contact Ethical Bridge through its official website.</p><p>This page describes the implemented data handling. Ethical Bridge’s applicable privacy terms also govern the shared account service.</p>`,
  ],
  safeguarding: [
    "Working responsibly",
    "Good intentions need good boundaries.",
    `<h2>Before a contribution begins</h2><p>Agree on the output, expected hours, deadlines, contact person and review process. Define what is out of scope. Clarify who owns the work and which parts, if any, can be used in a public portfolio.</p><h2>Protect people and information</h2><p>Use anonymised examples and the minimum necessary access. Do not upload beneficiary names, case files, identity documents, passwords or confidential research to a public profile or portfolio.</p><p>For work involving children, vulnerable people, legal advice, health information or financial decisions, the organisation must establish appropriate supervision, qualifications, consent and safeguarding procedures before granting access. A platform profile is not a background check or professional licence.</p><h2>Be precise about evidence</h2><p>Portfolio outcomes are self-reported. An organisation’s approval of hours confirms its review of a contribution record; it is not an independent certification of every claim. Ethical Bridge remains responsible for its own organisation publication and verification process.</p><h2>Raise a concern</h2><p>Pause work if scope, conduct or access becomes unsafe. Contact the organisation’s designated safeguarding lead and use Ethical Bridge’s official contact route for platform concerns. For immediate danger, use the appropriate local emergency service.</p><a href="https://ethicalbridge.org/" target="_blank" rel="noopener">Visit Ethical Bridge ↗</a>`,
  ],
};
