import { responsibility } from "./alliance.js";
export const guides = {
  guide: [
    "How it works",
    "Professional support, with clear expectations.",
    `<h2>For talent</h2><ol><li>Create your profile, describe your experience and set realistic monthly availability.</li><li>Explore the labelled example profiles to see how contributions become an impact CV. Add an optional LinkedIn URL to your professional profile.</li><li>Publish your profile to appear in the directory. Explore needs, save interesting ones and apply with a specific explanation of how you can help.</li><li>Check your workspace for decisions and invitations. When a match is accepted, read and sign the contribution agreement covering scope, timing, access, safeguarding, confidentiality and communication.</li><li>Log contributions after both parties sign. The organisation reviews them; approval is retained in your private contribution history. Public portfolios will be generated from reviewed contributions; the complete template is currently demonstrated with labelled examples.</li></ol><h2>For organisations</h2><ol><li>Use your Ethical Bridge organisation account. An existing organisation member can manage the workspace; new organisations start through Ethical Bridge.</li><li>Write a clear need: expected output, required skills, estimated hours and working arrangements. Drafts stay private until your organisation is published and you open the need.</li><li>Browse talent profiles and portfolios, invite suitable people and review applications.</li><li>Accept a suitable match, then read and sign the contribution agreement. Review submitted time with a clear explanation when changes are needed.</li><li>Close the need when you stop accepting applications.</li></ol><h2>Keep the relationship clear</h2><p>The in-platform contribution agreement records the accepted need, expected output, working details and both signatures. Add separate written terms where an engagement involves payment, expenses, regulated work, intellectual property or requirements beyond that scope.</p>`,
  ],
  privacy: [
    "Privacy & storage",
    "You choose what you share.",
    `<h2>Public and private information</h2><p>Profiles start private. Publishing makes your name, professional details, location, skills and availability visible in the directory. Public portfolio layouts currently use clearly labelled examples. Real contribution records remain private to participants until public contribution publishing is implemented. Do not put private contact details or beneficiary information in public fields.</p><p>Applications, invitations, conversations and time entries are visible to the participating professional and the relevant organisation members. Account email addresses are managed by Supabase Auth and are not displayed in the public directory.</p><h2>Storage and external services</h2><p>Account and platform records are stored in Ethical Bridge’s Supabase service. Authentication uses browser storage to keep you signed in. Sign out on shared devices. This app does not include advertising or analytics trackers, so there are no optional analytics cookies to accept.</p><p>Uploaded thumbnails use private storage and time-limited viewing links. A previously issued link can remain valid for up to one hour after unpublishing. Alternatively, thumbnails load from the external HTTPS address supplied by their author. The image provider receives a network request, including the visitor’s IP address; the app sends no referrer. Supporting links open external sites with their own privacy practices.</p><h2>Control your information</h2><p>Unpublish your profile to remove it from public browsing. You can edit your profile and withdraw pending applications. Previously saved manual portfolio records are retained but are no longer shown in the product. Submitted contribution and review records remain available to the participants for accountability. For account deletion or other data requests, contact Ethical Bridge through its official website.</p><p>This page describes the implemented data handling. Ethical Bridge’s applicable privacy terms also govern the shared account service.</p>`,
  ],
  safeguarding: [
    "Working responsibly",
    "Good intentions need good boundaries.",
    `<h2>Before a contribution begins</h2><p>Agree on the output, expected hours, deadlines, contact person and review process. Define what is out of scope. Clarify who owns the work and which parts, if any, can be used in a public portfolio.</p><h2>Protect people and information</h2><p>Use anonymised examples and the minimum necessary access. Do not upload beneficiary names, case files, identity documents, passwords or confidential research to a public profile or portfolio.</p><p>For work involving children, vulnerable people, legal advice, health information or financial decisions, the organisation must establish appropriate supervision, qualifications, consent and safeguarding procedures before granting access. A platform profile is not a background check or professional licence.</p><h2>Be precise about evidence</h2><p>Example endorsements, ratings and outcomes are illustrative. Future public impact records will be generated from contributions and organisation review. An organisation’s approval of hours confirms its review of a contribution record; it is not an independent certification of every claim. Ethical Bridge remains responsible for its own organisation publication and verification process.</p><h2>Sharing information and access</h2><p>Establish a trusted working relationship and agree confidentiality before exchanging sensitive work information. Share only what is necessary through an agreed secure channel. Never share passwords, payment-card details, PINs or one-time access codes through the platform. Use individual accounts with only the access needed.</p><h2>Your responsibilities & our limits</h2>${responsibility}<h2>Raise a concern</h2><p>Pause work if scope, conduct or access becomes unsafe. Contact the organisation’s designated safeguarding lead and use Ethical Bridge’s official contact route for platform concerns. For immediate danger, use the appropriate local emergency service.</p><a href="https://ethicalbridge.org/" target="_blank" rel="noopener">Visit Ethical Bridge ↗</a>`,
  ],
};
